## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np 

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
0,153,Warmbad,NaN,65.84,few clouds,-28.4500,18.7333,NaN
1,270,Lasa,IT,65.03,broken clouds,46.6166,10.7002,Pension Feldg채rtenhof
2,296,General Cepeda,MX,65.07,overcast clouds,25.3833,-101.4500,Hacienda Los Jose
3,322,Viersen,DE,65.10,broken clouds,51.2500,6.3833,Hotel Rahserhof
4,357,Grinnell,US,65.59,mist,41.7430,-92.7224,"Country Inn & Suites by Radisson, Grinnell, IA"

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} 째F</dd>
</dl>
"""
# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
vacation_df

,City_ID,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
0,153,Warmbad,NaN,65.84,few clouds,-28.4500,18.7333,NaN
1,270,Lasa,IT,65.03,broken clouds,46.6166,10.7002,Pension Feldg채rtenhof
2,296,General Cepeda,MX,65.07,overcast clouds,25.3833,-101.4500,Hacienda Los Jose
3,322,Viersen,DE,65.10,broken clouds,51.2500,6.3833,Hotel Rahserhof
4,357,Grinnell,US,65.59,mist,41.7430,-92.7224,"Country Inn & Suites by Radisson, Grinnell, IA"
5,361,Marawi,PH,65.64,broken clouds,7.9986,124.2928,Derogongan Residence
6,431,Chynadiyovo,UA,65.61,broken clouds,48.4818,22.8217,Vorobey
7,606,Broken Hill,AU,65.70,overcast clouds,-31.9500,141.4333,Royal Exchange Hotel
8,627,Piney Green,US,65.89,clear sky,34.7160,-77.3202,Holiday City Mobile Home Community
9,636,Erenhot,CN,65.17,overcast clouds,43.6475,111.9767,Erenhot Rurouni Youth Hostel

In [6]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"] == "Grinnell"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Grinnell"]

vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Broken Hill"] 
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Viersen"] 
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Erenhot"]

In [7]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
end = vacation_end["Lat"].to_numpy()[0], vacation_end["Lng"].to_numpy()[0]


stop1 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop1["Lng"].to_numpy()[0]
stop2 = vacation_stop2["Lat"].to_numpy()[0], vacation_stop2["Lng"].to_numpy()[0]
stop3 = vacation_stop3["Lat"].to_numpy()[0], vacation_stop3["Lng"].to_numpy()[0]

In [8]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
city_itinerary = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='DRIVING')

fig.add_layer(city_itinerary)
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# 8. To create a marker layer map between the four cities.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3, vacation_end],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
0,357,Grinnell,US,65.59,mist,41.7430,-92.7224,"Country Inn & Suites by Radisson, Grinnell, IA"
1,606,Broken Hill,AU,65.70,overcast clouds,-31.9500,141.4333,Royal Exchange Hotel
2,322,Viersen,DE,65.10,broken clouds,51.2500,6.3833,Hotel Rahserhof
3,636,Erenhot,CN,65.17,overcast clouds,43.6475,111.9767,Erenhot Rurouni Youth Hostel
4,357,Grinnell,US,65.59,mist,41.7430,-92.7224,"Country Inn & Suites by Radisson, Grinnell, IA"

In [10]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} 째F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [11]:
# 11a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))